### PR TITLE
Add in Google Maps API changes to master branch

### PR DESCRIPTION
**Pull request by 0xvincenzo**

### CODE REVIEW

**Comment by elliotda** [comment]
That should be everything for google maps api. I'll double check the master right now.

**Comment by elliotda** [comment]
I'm going to manually add them in. I'm afraid if I mess with merging while I have no idea what I'm doing i'll break what we have done. I feel safer adding them one at a time..Sorry I'm not very comfortable with all the github merge features.. :(

**Comment by 0xvincenzo** [comment]
It's okay. I just want to make sure everybody has a log of their changes. I'm not sure if everything has to be merged into the master, but it's better to be safe than sorry. For the demo, I figured we will use the version that I have on my computer.

**Comment by elliotda** [comment]
Thanks Vince. I committed all of the changes and just double checked that they work (pulled master after I changed and started up the local server). Everything works on my end, also doubled checked that the add button populated the map correctly too. :)

**Pull request closed without merging**
